name: New Project Tidy
# on: create
on: push
jobs:
  tidy:
    name: Tidy
    runs-on: ubuntu-latest
    steps:
      - name: Clone the New Repository
        uses: actions/checkout@v3
      - run: |
          echo "::notice ::${{github.repository_owner}}"
          echo "::notice ::${{github.event.repository.name}}"
      - run: >
          sed --in-place 's/@PROJECT@/${{github.event.repository.name}}/g'
          CMakeLists.txt Tests/CMakeLists.txt
      - run: git status
