name: New Project Tidy
# on: create
on: push
jobs:
  tidy:
    name: Tidy
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::notice ::${{github.repository_owner}}"
          echo "::notice ::${{github.event.repository.name}}"
